services:
  rdctl-bot:
    image: ghcr.io/crazyuploader/rdctl-bot:latest
    container_name: rdctl-bot
    volumes:
      - ./config.yaml:/app/config.yaml
    ports:
      - "8089:8089"
    restart: unless-stopped
    logging:
      options:
        max-size: "128m"
